site:
  host: example.com
  origin_cert: |
    -----BEGIN CERTIFICATE-----
    MIIFdzCCA1+gAwIBAgISA0...
    ... (rest of your certificate content) ...
    -----END CERTIFICATE-----
  origin_key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvAIBADANBgkqhkiG9w0BA...
    ... (rest of your private key content) ...
    -----END PRIVATE KEY-----
